---
- name: install tomcat
  package:
    name: tomcat
    state: latest

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify: enable and start tomcat
...

