---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  copy:
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo
    mode: u=rw,g=r,o=r

- name: stat internal
  stat: path=/etc/yum.repos.d/internal.repo
  register: int_stat

- name: rm internal
  command: rm /etc/yum.repos.d/internal.repo
  when: int_stat.stat.exists

- name: stat epel
  stat: path=/etc/yum.repos.d/epel*
  register: epel_stat

- name: rm epel    
  command: rm /etc/yum.repos.d/epel*
  when: epel_stat.stat.exists

- name: Run yum clean
  command: yum clean all


- name: install base tools and packages
  yum:
    name: 
      - python3
      - git
      - ansible
    state: present
